[project]
name = "yourcontext"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alibabacloud-oss-v2>=1.2.1",
    "chromadb>=1.2.1",
    "langchain>=1.0.8",
    "langchain-core>=1.0.7",
    "langchain-mcp-adapters>=0.1.13",
    "langchain-openai>=1.0.3",
    "langgraph>=1.0.3",
    "langsmith>=0.4.44",
    "loguru>=0.7.3",
    "mcp>=1.21.2",
    "pydantic>=2.12.3",
    "python-dotenv>=1.1.1",
]

[dependency-groups]
dev = [
    "langgraph-cli[inmem]>=0.4.7",
    "pytest>=8.4.2",
    "pytest-html>=4.1.1",
    "pytest-ordering>=0.6",
]

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
pythonpath = [
  "."
]
log_cli = true
log_cli_level = "DEBUG"
log_format = "%(asctime)s %(levelname)s %(message)s"
log_date_format = "%Y-%m-%d %H:%M:%S"
generate_report_on_test = true
